CREATE DATABASE jcontactsdb;
GRANT ALL PRIVILEGES ON jcontactsdb.* TO 'jcontacts'@'%' IDENTIFIED BY 'jcpwd' WITH GRANT OPTION;
USE jcontactsdb;


CREATE TABLE CONTATTI(
   ID_CONTATTO INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
   NOME VARCHAR(128),
   COGNOME VARCHAR(128),
   EMAIL VARCHAR(256),   
   INDIRIZZO VARCHAR(1024),
   TELEFONO VARCHAR(10)
);
